#
# The do nothing makefile
#


all:

protocol:
	@echo MakeProcessProtocol

makecommand:
	@echo MakeCommand ${TEST1} ${TEST2}

release:
	@echo ReleaseBuilder: ${BUILDNAME} ${CHROOTDIR} ${CVSROOT} ${RELEASETAG} ${NOPORTS} ${NODOC}
