#
# The do nothing makefile
#


all:

protocol:
	@echo MakeProcessProtocol >${OUTPUT}

makecommand:
	@echo MakeCommand ${TEST1} ${TEST2} >${OUTPUT}

release:
	@echo ReleaseBuilder: ${BUILDNAME} ${CHROOTDIR} ${CVSROOT} ${RELEASETAG} ${NOPORTS} ${NODOC} >${OUTPUT}
