#!/usr/bin/env python
# farbctl vi:ts=4:sw=4:expandtab:
#
# Copyright (c) 2006 Three Rings Design, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright owner nor the names of contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import getopt, sys, os
import ZConfig
import shutil

from twisted.internet import reactor, defer, threads
from twisted.python import threadable 
threadable.init()

import farb
from farb import utils, builder, config

INDEX_PREFIX='INDEX'

def usage():
    print "Usage: %s [-h] [-f config file] [-r action]" % sys.argv[0]
    print "    -h             Print usage (this message)"
    print "    -f <config>    Use configuration file"
    print "    -r <action>    Execute <action>"
    print "\nSupported actions:"
    print "    release        Build all defined releases"

def main():
    conf_file = None
    action = None

    try:
        opts,args = getopt.getopt(sys.argv[1:], "hf:r:")
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    for opt,arg in opts:
        if opt == "-h":
            usage()
            sys.exit()
        if opt == "-f":
            conf_file = arg
        if opt == "-r":
            action = arg

    if (conf_file == None or action == None):
        usage()
        sys.exit(1)

    # a dictionary mapping packages to releases
    release_packages = {}
    # Load our configuration schema
    schema = ZConfig.loadSchema(farb.CONFIG_SCHEMA)
    try:
        farbconfig, handler = ZConfig.loadConfig(schema, conf_file)
        release_packages = config.verifyPackages(farbconfig)
    except ZConfig.ConfigurationError, e:
        print "Configuration Error: %s" % e
        sys.exit(1)

    # Set up logging
    try:
        farbconfig.Logging()
    except Exception, e:
        print "Log initialization failed: %s" % e
        sys.exit(1)

    # Execute requested action
    if (action == "release"):
        rbr = ReleaseBuildRunner(farbconfig, release_packages)
        rbr.run()
    else:
        print "Unknown action \"%s\".\n" % (action)
        usage()
        sys.exit(1)

    reactor.run()

class BuildContext(object):
    """
    Context associated with release and packaging builds.
    """
    def __init__(self, description, logPath):
        """
        @param description: Description of the build
        @param logPath: Path to log file, if any.
        """
        self.description = description
        self.logPath = logPath

class ReleaseBuildRunner(object):
    """
    Run a set of release builds, printing
    an error and stopping the reactor on failure.
    """
    def __init__(self, config, release_packages):
        self.logs = []
        self.oe = utils.OrderedExecutor()

        for release in config.Releases.Release:
            # Create the build directory
            buildroot = os.path.join(config.Releases.buildroot, release.getSectionName())
            netinstallroot = os.path.join(config.Releases.netinstallroot, release.getSectionName())
            chroot = os.path.join(buildroot, 'chroot')
            packagesdir = os.path.join(netinstallroot, 'packages')
            portsdir = os.path.join(chroot, 'usr', 'ports')
            portspackagesdir = os.path.join(portsdir, 'packages')

            try:
                if (not os.path.exists(buildroot)):
                    os.makedirs(buildroot)
            except Exception, e:
                print "Failed to create build root: %s" % (e)
                sys.exit(1)

            # Open the log file
            logPath = os.path.join(buildroot, 'build.log')
            buildLog = open(logPath, 'w', 0)
            self.logs.append(buildLog)

            rb = builder.ReleaseBuilder(release.cvsroot, release.cvstag, buildroot)

            # Add our builder to the OrderedExecutor
            bctx = BuildContext("%s release build" % release.getSectionName(), logPath)
            eu = utils.ExecutionUnit(bctx, rb.build, buildLog)
            self.oe.appendExecutionUnit(eu)

            # checkout the ports tree into the chroot 
            cvs = builder.CVSCommand(release.cvsroot)
            eu = utils.ExecutionUnit(None, cvs.export, 'HEAD', 'ports', portsdir, buildLog)
            self.oe.appendExecutionUnit(eu)

            # make the packages directory 
            if (not os.path.exists(portspackagesdir)):
                eu = utils.ExecutionUnit(None, defer.execute, os.mkdir, portspackagesdir) 
                self.oe.appendExecutionUnit(eu)

            # Add package builds to the OrderedExecutor
            releaseName = release.getSectionName()
            packageList = release_packages.get(releaseName)
            # if asked to build no packages go onto the next release 
            if (not packageList):
                continue

            for package in packageList:
                # Open a per-package log file
                logPath = os.path.join(buildroot, package.package+'.log')
                packageLog = open(logPath, 'w', 0)
                self.logs.append(packageLog)
                buildoptions = {}
                if package.BuildOptions:
                    buildoptions = package.BuildOptions.Options
                pb = builder.PackageBuilder(chroot, package.port, buildoptions)
                # Add our package builder to the OrderedExecutor
                bctx = BuildContext("%s package build" % package.package, logPath)
                eu = utils.ExecutionUnit(bctx, pb.build, packageLog)
                self.oe.appendExecutionUnit(eu)

            # grab the current index
            index = builder.MakeCommand('/usr/ports', ['fetchindex'], chrootdir=chroot)
            eu = utils.ExecutionUnit(None, index.make, buildLog)
            self.oe.appendExecutionUnit(eu)

            # clean the netinstall release directory
            if (os.path.exists(netinstallroot)):
                eu = utils.ExecutionUnit(None, threads.deferToThread, shutil.rmtree, netinstallroot) 
                self.oe.appendExecutionUnit(eu)

            # copy the release into the netinstall root
            eu = utils.ExecutionUnit(None, threads.deferToThread, shutil.copytree, os.path.join(chroot, 'R', 'ftp'), netinstallroot, 1)
            self.oe.appendExecutionUnit(eu)

            # copy the packages into the netinstall root
            eu = utils.ExecutionUnit(None, threads.deferToThread, shutil.copytree, os.path.join(portsdir, 'packages'), packagesdir, 1)
            self.oe.appendExecutionUnit(eu)

            # copy the package INDEX files into the netinstall root
            for dir in os.listdir(portsdir):
                if (dir[:len(INDEX_PREFIX)] == INDEX_PREFIX):
                    eu = utils.ExecutionUnit(None, threads.deferToThread, shutil.copy2, os.path.join(portsdir, dir), packagesdir)
                    self.oe.appendExecutionUnit(eu)

    def _closeLogs(self):
        # Close all the log files
        for logFile in self.logs:
            logFile.close()

    def _cbReleaseBuild(self, result):
        print "Release Build Complete"
        self._closeLogs()

        reactor.stop()

    def _ebReleaseBuild(self, failure):
        try:
            # Grab the BuildContext and raise the original exception
            bctx = failure.value.executionContext
            failure.value.originalFailure.raiseException()
        except builder.ReleaseBuildError, e:
            print "%s failed: %s" % (bctx.description, e)
            print "For more information, refer to the release build log: %s" % (bctx.logPath)
        except builder.PackageBuildError, e:
            print "%s failed: %s" % (bctx.description, e)
            print "For more information, refer to the package build log: %s" % (bctx.logPath)
        except Exception, e:
            print "Unhandled Release Build Error: %s" % (e)

        self._closeLogs()
        reactor.stop()

    def run(self):
        # Run!
        d = self.oe.run()
        d.addCallback(self._cbReleaseBuild)
        d.addErrback(self._ebReleaseBuild)


if __name__ == "__main__":
    main()
